name: tender_andres
services:
  cria:
    build:
      context: /tmp
      dockerfile: Dockerfile-gpu
    cpu_shares: 90
    command: []
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          devices:
            - capabilities:
                - gpu
              driver: nvidia
              count: 1
    environment:
      - CRIA_GPU_LAYERS=1
      - CRIA_HOST=0.0.0.0
      - CRIA_PORT=3000
      - CRIA_SERVICE_NAME=cria
      - CRIA_USE_GPU=true
      - CRIA_ZIPKIN_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    image: ghcr.io/aminediro/cria:gpu
    labels:
      icon: https://icon.casaos.io/main/all/cria.png
    ports:
      - target: 3000
        published: "3069"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/cria/models/llama-2-13b-chat.ggmlv3.q4_K_M.bin
        target: /app/model.bin
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
    container_name: ""
  zipkin:
    cpu_shares: 90
    command: []
    container_name: zipkin-server
    deploy:
      resources:
        limits:
          memory: 11897M
    image: openzipkin/zipkin
    labels:
      icon: https://icon.casaos.io/main/all/cria.png
    ports:
      - target: 9411
        published: "9411"
        protocol: tcp
    restart: unless-stopped
    volumes: []
    devices: []
    cap_add: []
    environment: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: self
  category: self
  hostname: ""
  icon: https://icon.casaos.io/main/all/cria.png
  index: /
  port_map: "9411"
  scheme: http
  store_app_id: tender_andres
  title:
    custom: llama 2
